# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.9
_src_path: gh:seedcase-project/template-python-package
author_email: lwjohnst@gmail.com
author_family_name: Johnston
author_given_name: Luke William
copyright_year: '2025'
github_board_number: '18'
github_repo: check-datapackage
github_user: seedcase-project
hosting_provider: netlify
is_seedcase_project: true
review_team: '@seedcase-project/developers'
